dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib
env:
  global:
  - NJOBS=2
  - COQ_REPOS=https://github.com/coq/coq.git
  - COQ_VERSION="v8.7"
  - COQ_BRANCH="v8.7"
  - COMPILER="4.06.0"
  - BASE_OPAM="camlp5 cmdliner ppx_deriving ppx_import ppx_sexp_conv sexplib"
  # Main test suites
  matrix:
  - TEST_TARGET="all"
  - TEST_TARGET="sertop_js.js" COMPILER="4.06.0+32bit" EXTRA_OPAM="js_of_ocaml js_of_ocaml-let ppx_deriving_yojson" COQ_EXTRA_MAKE="byte"
  # Add COQ_EXTRA_CONF="-bytecode-compiler no" to 8.8
  # - TEST_TARGET="test2"

install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam config var root
- opam update
- opam install -j ${NJOBS} -y ${BASE_OPAM} ${EXTRA_OPAM} # yojson ppx_deriving_yojson
- opam list
- git clone --depth=3 -b ${COQ_BRANCH} ${COQ_REPOS} ${HOME}/coq-${COQ_VERSION}
- pushd ${HOME}/coq-${COQ_VERSION}
- ./configure -local -native-compiler no -coqide no ${COQ_EXTRA_CONF}
- make -j ${NJOBS}
- make -j ${NJOBS} ${COQ_EXTRA_MAKE}
- popd

script:
- echo 'Building SerAPI...' && echo -en 'travis_fold:start:serapi.build\\r'
# - make -j ${NJOBS} SERAPI_COQ_HOME="${HOME}/coq-${COQ_VERSION}/" serlib
# - ls -l _build/serlib/serlib.cmxa
- make -j ${NJOBS} SERAPI_COQ_HOME="${HOME}/coq-${COQ_VERSION}/" TEST_TARGET
- ls -l _build/sertop/
- echo -en 'travis_fold:end:serapi.build\\r'
