dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    packages:
    - gcc-multilib
env:
  global:
  - OPAMJOBS="2"
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - NJOBS="2"
  - COQ_REPOS="https://github.com/coq/coq.git"
  - COQ_VERSION="v8.8"
  - COQ_BRANCH="v8.8"
  - COQ_CONF="-local -native-compiler no -coqide no"
  - COMPILER="4.06.1"
  - BASE_OPAM="camlp5 cmdliner ppx_deriving ppx_import ppx_sexp_conv sexplib"
  # Main test suites
  matrix:
  # Don't test opam in 8.8 yet.
  - TEST_TARGET="all"                                                                               EXTRA_OPAM="coq"
  - TEST_TARGET="all"             COMPILER="4.06.1"       SERAPI_COQ_HOME="$HOME/coq-$COQ_VERSION/"
  - TEST_TARGET="all"             COMPILER="4.07.0"       SERAPI_COQ_HOME="$HOME/coq-$COQ_VERSION/"
  - TEST_TARGET="js/sertop_js.js" COMPILER="4.06.1+32bit" SERAPI_COQ_HOME="$HOME/coq-$COQ_VERSION/" EXTRA_OPAM="js_of_ocaml js_of_ocaml-lwt ppx_deriving_yojson" COQ_EXTRA_MAKE="byte"
  # Add COQ_EXTRA_CONF="-bytecode-compiler no" to 8.8
  # - TEST_TARGET="test2"

install:
- echo "yes" | sudo add-apt-repository ppa:ansible/bubblewrap
- sudo apt-get update -qq
- sudo apt-get install -qq bubblewrap
- sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.0/opam-2.0.0-x86_64-linux -o /usr/bin/opam
- sudo chmod 755 /usr/bin/opam
- opam init -c "$COMPILER"
- opam switch set "$COMPILER"
- eval $(opam env)
- opam install $BASE_OPAM $EXTRA_OPAM # yojson ppx_deriving_yojson
- opam list
- >
  if [[ -v SERAPI_COQ_HOME ]]; then
    git clone --depth=3 -b "$COQ_BRANCH" "$COQ_REPOS" "$HOME/coq-$COQ_VERSION" &&
    pushd "$HOME/coq-$COQ_VERSION"        &&
    ./configure $COQ_CONF $COQ_EXTRA_CONF &&
    make -j "$NJOBS"                      &&
    make -j "$NJOBS" $COQ_EXTRA_MAKE      &&
    popd;
  fi

script:
- echo 'Building SerAPI...' && echo -en 'travis_fold:start:serapi.build\\r'
- make -j "$NJOBS" SERAPI_COQ_HOME="$SERAPI_COQ_HOME" "$TEST_TARGET"
- ls -l _build/sertop/
- echo -en 'travis_fold:end:serapi.build\\r'
